# Generated by Django 5.2.9 on 2026-01-01 07:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('node_type', models.CharField(choices=[('technology', 'Technology')], default='technology', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('level', models.IntegerField(default=0, help_text='Skill level between 0 and 5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('prerequisite', 'Prerequisite'), ('used_with', 'Used With'), ('alternative', 'Alternative'), ('related', 'Related'), ('built_on', 'Built On')], max_length=50)),
                ('strength', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='skills.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='skills.node')),
            ],
            options={
                'db_table': 'relations',
            },
        ),
        migrations.CreateModel(
            name='CardSelection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.node')),
            ],
            options={
                'db_table': 'card_selections',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('node',), name='unique_card_selection_node')],
            },
        ),
    ]
